server:
  port: 8080
  servlet:
    context-path: /movies-web
  
spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
    hibernate:
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
   
  datasource:
    platform: mysql
    url: "jdbc:mysql://localhost:3306/movieDB?serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: spring
    password: spring1234
    
# Edit to match your own file system
photoTempDir: "/home/dominique/Pictures/tmp/"
